//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseCode { get; set; }
        public string CourseName { get; set; }
        public string CourseSubmition { get; set; }
        public decimal CoursGrade { get; set; }
        public int PcnNumber { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
